#include <greeter/io/MagnetIO.h>
#include <greeter/io/ArrangementFactoryIO.h>
#include <greeter/io/MethodFactoryIO.h>
#include <greeter/io/SceneIO.h>
#include <set>


namespace greeter {

    MagnetIO::MagnetIO() {}

    MagnetIO::~MagnetIO() {}

    bool MagnetIO::validateJSON(const nlohmann::json& data) {

        std::set<std::string> fov_keys = {"x", "y", "z"};

        // Magnets may be listed one by one, generated by an arrangement, or
        // both, but a file that describes none of them describes nothing.
        if (!data.contains("magnets") && !data.contains("arrangements")) {
            return false;
        }

        // A field of view is only needed for a magnetic field simulation, an
        // input file that only asks for forces may leave it out.
        if (!data.contains("force") && !data.contains("field_of_view")) {
            return false;
        }

        // The types that can be read are the ones the registries hold, which
        // is one list rather than a copy of it kept here that goes stale as
        // soon as a type is added.
        if (data.contains("magnets")) {
            for (const auto& magnet : data["magnets"]) {
                if (!magnet.contains("type") || !magnet["type"].is_string()) {
                    return false;
                }
                if (!MethodFactoryIO::getInstance().isRegistered(
                        magnet["type"].get<std::string>())) {
                    return false;
                }
            }
        }

        if (data.contains("arrangements")) {
            for (const auto& arrangement : data["arrangements"]) {
                if (!arrangement.contains("type") || !arrangement["type"].is_string()) {
                    return false;
                }
                if (!ArrangementFactoryIO::getInstance().isRegistered(
                        arrangement["type"].get<std::string>())) {
                    return false;
                }
            }
        }

        // Verify the field of view
        if (data.contains("field_of_view")) {
            for (auto& fov_key : fov_keys) {
                if (!data["field_of_view"].contains(fov_key)) {
                    return false;
                }
            };
        };

        // The parameters of a magnet are checked by the reader of its own type,
        // which is the only place that knows what its shape takes.
        return true;
    };

    greeter::MagnetCollection MagnetIO::read(const nlohmann::json& data) {

        // The magnets alone. A caller that also needs to know which id each of
        // them answers to, as the force section does, reads the whole scene.
        return std::move(SceneIO::read(data).collection);
    }

    greeter::FieldOfView MagnetIO::readFieldOfView(const nlohmann::json& fov) {

        std::vector<std::string> keys = {"x", "y", "z"};

        for (auto& key : keys) {
            if (!fov.contains(key)) {
                throw std::invalid_argument("Invalid field of view");
            }
        }

        std::vector<float> xxyyzz = {
            fov["x"]["min"],
            fov["x"]["max"],
            fov["y"]["min"],
            fov["y"]["max"],
            fov["z"]["min"],
            fov["z"]["max"]
        };

        std::vector<u_int32_t> nnn = {
            fov["x"]["n"],
            fov["y"]["n"],
            fov["z"]["n"]
        };

        return greeter::FieldOfView(xxyyzz, nnn);
    }
}  // namespace greeter
